### ISSUE TITLE
What would be the steps to add a new product?

### ISSUE THREAD

**Issue by wolfdancer** [rackerlabs/pitchfork#33]
Hello, I would like to learn how Cloud Metrics API can be added here:

http://docs.rackspace.com/cmet/api/v1.0/cmet-devguide/content/api-operations-external.html

Thanks!

**Comment by oldarmyc** [comment]
If this is your own instance then you can go to 
URL/PRODUCT_NAME/manage

Add in the parameters for the product, and start adding in the API calls. On the public instance I will work on getting the calls in soon as I am working on some changes to fix the layout and some other additions.
