### ISSUE TITLE
Agent Check Types

### ISSUE THREAD

**Issue by jacob0719** [rackerlabs/pitchfork#34]
It looks like in the GUI, some of the check types are not listed:

CheckType: id=agent.mssql_version
CheckType: id=agent.mssql_database
CheckType: id=agent.mssql_buffer_manager
CheckType: id=agent.mssql_sql_statistics
CheckType: id=agent.mssql_memory_manager
CheckType: id=agent.mssql_plan_cache

Could these types be added?

**Comment by oldarmyc** [comment]
Added additional checks to the new location of the application that has been deployed.

https://cloudapi.co
