### ISSUE TITLE
meta_value does not accept strings when creating server

### ISSUE THREAD

**Issue by lesma** [rackerlabs/pitchfork#42]
On the current version at https://pitchfork.cloudapi.co/. When creating a server the meta_value attribute only accepts Boolean values, if using something like the RackConnnect Auto NAT feature http://www.rackspace.com/knowledge_center/article/rackconnect-auto-nat-feature need to type an IP address into this field. It would also be nice if you could add additional items of metadata when creating a server.

You were able to type in a IP address into the meta_value in a previous version.

**Comment by oldarmyc** [comment]
Call has been corrected.
